inputs:
  app_name:
    description: Nome da aplicação
    required: true
  image_repo:
    description: Repositório da imagem Docker
    required: true
  image_tag:
    description: Tag da imagem Docker
    required: true
  chart:
    description: Caminho do chart Helm
    required: true
